In [1]:
import numpy as np
arr = np.random.randint(1,100, size=(10,5)) # sample - 10, feature - 5
print(arr)
print(arr.shape)

[[55 67 61 78 48]
 [49 93 69 56 17]
 [39 62 17  3 72]
 [88 83 41 42 25]
 [54 23 32 90 70]
 [10 86 35 89 83]
 [44 97 67 76 40]
 [ 8 18 64  9 77]
 [74 59 73 88 53]
 [78 80  2  3 53]]
(10, 5)


In [2]:
## Reshaping an array from (10,5) to (5,10)
## Using flatten arrays are maked into 1 dimentioned array. It does row wise flattening

b = arr.reshape(5,10)
print(b)
b.ndim
flatten = b.flatten()
print(flatten.ndim)
print(flatten)

## Column wise flattening using ravel
collumn_wise_flattening = np.ravel(b, order='F')  ## for row wise orderr, order='c'
print(collumn_wise_flattening)

[[55 67 61 78 48 49 93 69 56 17]
 [39 62 17  3 72 88 83 41 42 25]
 [54 23 32 90 70 10 86 35 89 83]
 [44 97 67 76 40  8 18 64  9 77]
 [74 59 73 88 53 78 80  2  3 53]]
1
[55 67 61 78 48 49 93 69 56 17 39 62 17  3 72 88 83 41 42 25 54 23 32 90
 70 10 86 35 89 83 44 97 67 76 40  8 18 64  9 77 74 59 73 88 53 78 80  2
  3 53]
[55 39 54 44 74 67 62 23 97 59 61 17 32 67 73 78  3 90 76 88 48 72 70 40
 53 49 88 10  8 78 93 83 86 18 80 69 41 35 64  2 56 42 89  9  3 17 25 83
 77 53]


### Concatanate

In [16]:
a = np.random.randint(1,10, size =(2,3))
b = np.random.randint(20,30, size =(2,3))
print(a)
print(b)

[[1 8 5]
 [3 1 5]]
[[29 20 27]
 [20 24 21]]


In [18]:
con_row = np.concatenate((a,b), axis=0) # row wise
print(con_row)
con_col = np.concatenate((a,b), axis=1) # column wise
print(con_col)

[[ 1  8  5]
 [ 3  1  5]
 [29 20 27]
 [20 24 21]]
[[ 1  8  5 29 20 27]
 [ 3  1  5 20 24 21]]


In [21]:
## Dimension needs to be matched for concatenation
x = np.random.randint(1,10, size =(2,3))
y = np.random.randint(20,30, size =(1,3))
print(x)
print(y)
con_row = np.concatenate((x,y), axis = 0) ## will work, because row dimentioned matched
con_col = np.concatenate((x,y), axis = 1) ## will not work because column dimension missmatched

[[9 3 9]
 [6 2 5]]
[[21 26 27]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

### Transpose Matrix

In [22]:
mat = np.array([[10,20,30],[40,50,60]])
transpose = mat.T
print(transpose)

[[10 40]
 [20 50]
 [30 60]]


### Array Split

In [26]:
a = np.random.randint(1,10, size =(10,))

## not equal division
splitted_array = np.array_split(a,3)
print(splitted_array)

## equal division
splitted_array = np.split(a,3) ## will not work because array can not be devided equally

[array([8, 5, 6, 6], dtype=int32), array([3, 1, 9], dtype=int32), array([9, 1, 5], dtype=int32)]


ValueError: array split does not result in an equal division

### Arithmatic Operator & Mathmatical Function

In [29]:
## Faster for vectorization
x = np.array([10,20,30,40])
y = np.array([2,3,4,5])

add = x+y
print(add)

sub = x-y
print(sub)

multi = x*y
print(multi)

div = x/y
print(div)

reminder = x%y
print(reminder)

[12 23 34 45]
[ 8 17 26 35]
[ 20  60 120 200]
[5.         6.66666667 7.5        8.        ]
[0 2 2 0]


In [31]:
## mathematical function

## trigonometry
## sin, cos, tan takes value in radian
sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

[-0.54402111  0.91294525 -0.98803162  0.74511316]
[-0.83907153  0.40808206  0.15425145 -0.66693806]
[ 572.95779513 1145.91559026 1718.87338539 2291.83118052]


In [37]:
## Log
# 10 diye koybar vaag kora jay
base_10_log_val = np.log10(x)
print(base_10_log_val)

# 2 diye koybar vag kora jay
two_diye_vag = np.log2(x)
print(two_diye_vag)

# square root
sqrt = np.sqrt(x)
print(sqrt)

# sum
s = np.sum(x)
print(s)

# cumulative sum
cumulitive = np.cumulative_sum(x)
print(cumulitive)

[1.         1.30103    1.47712125 1.60205999]
[3.32192809 4.32192809 4.9068906  5.32192809]
[3.16227766 4.47213595 5.47722558 6.32455532]
100
[ 10  30  60 100]


### Broadcasting

In [40]:
x = np.array([10,20,30,40])
result = x**2
print(result)

[ 100  400  900 1600]


In [44]:
mat = np.array([[10,20,30],
                [40,50,60]
               ])
#print(mat)
result = mat+2
#print(result)

vector = np.array([10,20,30])
sumation = mat+vector
print(sumation)

[[20 40 60]
 [50 70 90]]


### Comparison - >, <, <=, >=, ==, !=

In [51]:
x = np.array([10,20,30,40])
y = np.array([2,3,30,5])

greater_than = x>y
print(greater_than)

equal = x ==y
print(equal)

# all() -> shob true kina
# any() -> je kono ekta true kina
print(np.all(greater_than))
print(np.any(equal))

[ True  True False  True]
[False False  True False]
False
True


### Sorting

In [56]:
## In place sorting does not copy the original one, instead change the original one
x = np.array([10,2,30,40])
z = x.copy()
print(z)
z.sort()
print(z)

## copy the original array. does not change original one
x = np.array([10,2,5,40])
sort_arr = np.sort(x)
print(sort_arr)
print(x)

[10  2 30 40]
[ 2 10 30 40]
[ 2  5 10 40]
[10  2  5 40]


In [58]:
## 2d array sorting
mat = np.array([[10,3,5],[8,4,9]])

# horizontal sort. axis =1
hor_sort = np.sort(mat, axis=1)
print(hor_sort)

# vertical sort. axis =0
ver_sort = np.sort(mat, axis=0)
print(ver_sort)

[[ 3  5 10]
 [ 4  8  9]]
[[ 8  3  5]
 [10  4  9]]


### Searching

In [59]:
print(x)

[10  2  5 40]


In [68]:
# np.where(condition, x, y) if true x, otherwise replace with y
index = np.where(x==5)
print(index)

index = np.where(x>=5)
print(index)

index = np.where(x>5,x,0)  # returns array. ## np.where(condition, x, y) if true x, otherwise replace with y
print(index)

## Maximum index & Minimum index
print(x)
maximum_value_index = np.argmax(x)
minimum_value_index = np.argmin(x)

print(maximum_value_index)
print(minimum_value_index)

(array([2]),)
(array([0, 2, 3]),)
[10  0  0 40]
[10  2  5 40]
3
1


### Counting

In [76]:
x = np.random.randint(1,100, size =(100,))
print(x)

## np.count_nonzero
value_greater_than_60 = np.count_nonzero(x>100)
print(value_greater_than_60)

## np.unique
unique_value, count = np.unique(x, return_counts=True)
print(unique_value)
print(count)

[93 19 54 74 62 42 37 72 51 20 78 79 20 15 36 11 73 64 72 99 82 58 17 50
 38 57 41 53  7 76 60 43 81  1 34 79 18 53 63 40  2 18 68 84 52 26 64 92
  4 36 67 39 51 25  6  9 30 70 93 26 18 14 36 38 26  2 25 14 21  5 10 47
 78 83 15 13 34 34 30 16 66 33  5 34 17 43 40 52 37  1 41 69 46 93  9 67
 38 23 45 88]
0
[ 1  2  4  5  6  7  9 10 11 13 14 15 16 17 18 19 20 21 23 25 26 30 33 34
 36 37 38 39 40 41 42 43 45 46 47 50 51 52 53 54 57 58 60 62 63 64 66 67
 68 69 70 72 73 74 76 78 79 81 82 83 84 88 92 93 99]
[2 2 1 2 1 1 2 1 1 1 2 2 1 2 3 1 2 1 1 2 3 2 1 4 3 2 3 1 2 2 1 2 1 1 1 1 2
 2 2 1 1 1 1 1 1 2 1 2 1 1 1 2 1 1 1 2 2 1 1 1 1 1 1 3 1]


### Statistical Function

In [1]:
# np.max()
# np.min()
# np.mean() -> average
# np.median()
# np.std() -> standard deviation
# np.corrcoef()

### Linear Algebra

In [13]:
import numpy as np
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])

# Matrix Multiplication
dot_product = np.dot(A,B) # Matrix Multiplication
print(dot_product)

# Trace ber kora
print(np.trace(B)) # diagonal borabor value gula sumation kore

# Determinent ber kora

sq_mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(sq_mat.shape)
det_of_sq = np.linalg.det(sq_mat)
print(det_of_sq)

# Rank ber kora
rank_of_sq = np.linalg.matrix_rank(sq_mat)
print(rank_of_sq)

[[19 22]
 [43 50]]
13
(3, 3)
-9.51619735392994e-16
2


In [12]:
arr = np.array([1,2,3,4,5,6])
b = arr.reshape(2,3)
print(b.shape)
print(np.sin(np.pi/2))

(2, 3)
1.0


In [4]:
print("Hello World")

Hello World
