### Array creation with random value

In [3]:
## np.random.rand
import numpy as np
arr = np.random.rand(2,3)
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(type(arr))

[[0.27546809 0.43333125 0.30358353]
 [0.01976688 0.7613784  0.9568835 ]]
(2, 3)
float64
2
6
<class 'numpy.ndarray'>


In [2]:
## np.random.randint
arr = np.random.randint(1,5,(2,3))
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(type(arr))

[[2 1 2]
 [3 4 2]]
(2, 3)
int32
2
6
<class 'numpy.ndarray'>


In [10]:
## np.random.uniform
arr = np.random.uniform(1,5,(2,3))
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(type(arr))

[[3.76635625 3.84471045 2.87170317]
 [1.27262553 3.30980154 3.0259492 ]]
(2, 3)
float64
2
6
<class 'numpy.ndarray'>


### Array creation with np.arange function

In [70]:
## np.arange(start, end, steps) & np.reshape()
arr = np.arange(1,10,1).reshape(3,3)
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(type(arr))
print("........................")
## np.linspace(start, end, koyta)
arr = np.linspace(0, 10, 5)
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(type(arr))

## np.logspace(start, end, koyta)
arr = np.logspace(0,4,5, base=2)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int64
2
9
<class 'numpy.ndarray'>
........................
[ 0.   2.5  5.   7.5 10. ]
(5,)
float64
1
5
<class 'numpy.ndarray'>
[ 1.  2.  4.  8. 16.]


## Creating Matrix for linear algebra

In [25]:
## Diagonal Matrix & Identity Matrix
diagonal_matrix = np.diag([1,2,3,4])
print(diagonal_matrix)
print(diagonal_matrix.shape)

##  identity matrix. np.eye(row, coll, k)
iden = np.eye(4)
print(iden)
print(iden.shape)

## changing diagonal using k value of eye()
iden = np.eye(3,4,-1)
print(iden)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


## Indexing

In [33]:
arr1 = [1,2,3,4,5]
arr2 = [[1, 2, 3], [4, 5, 6]]

arr1 = np.array(arr1)
arr2 = np.array(arr2)
print(arr1[2])
arr1[2] = 100
print(arr1)
print(arr2[0][1])
arr2[0][1] = 100
print(arr2)

3
[  1   2 100   4   5]
2
[[  1 100   3]
 [  4   5   6]]


### Slicing

In [49]:
## 1d array slicing
# arr[start:end: step]
arr1_modified = arr1[1:4]
#print(arr1_modified)

## 2d array slicing
#arr[rowstart:rowend:rowstep,colstart:colend:colstep]
print(arr2)

print("...............")
# getting row 0
row0 = arr2[0:1,]

# getting row 1
row1 = arr2[1:,]

print(row0)
print(row1)
print("...............")

# getting a colum
colum0 = arr2[::, 0:1]
print(colum0)


[[  1 100   3]
 [  4   5   6]]
...............
[[  1 100   3]]
[[4 5 6]]
...............
[[1]
 [4]]


### Advanced indexing and iteration

In [65]:
## copy in array
print(arr1)
arr_modified = arr1[1:3].copy()
arr_modified[1] = 600
print(arr_modified)
print(arr1)

print(".....................")

## Advanced Slicing
ls = np.array([10,20,30,40,50,60])
print(ls)
values = ls[[1,3]]
print(values)

## advanced slicing for 2d array
print(".....................")
print(arr2)
print(arr2[[0,1],[1,2]])

# boolean operation
print(arr2[arr2>2])
arr2[arr2>2] = 0
print(arr2)

[  1   2 500   4   5]
[  2 600]
[  1   2 500   4   5]
.....................
[10 20 30 40 50 60]
[20 40]
.....................
[[  1 100   3]
 [  4   5   6]]
[100   6]
[100   3   4   5   6]
[[1 0 0]
 [0 0 0]]


In [67]:
## Iteration
arr = np.array([[10,20,30,40],[100,200,300,400]])
print(arr)
for i in np.nditer(arr):
    print(i)

[[ 10  20  30  40]
 [100 200 300 400]]
10
20
30
40
100
200
300
400


In [71]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr[:,1])

[20 50]
