In [1]:
import numpy as np
arr = np.random.randint(1,100, size=(10,5)) # sample - 10, feature - 5
print(arr)
print(arr.shape)

[[11 81 60 54 18]
 [68 76 62 63 14]
 [51 29 82 78 56]
 [52 25 60 99 21]
 [56 77 69 72 66]
 [90 55 95 26 19]
 [56 99  4 61 61]
 [77 62 48  4 45]
 [61 23 12 67 37]
 [23 33 41 92  6]]
(10, 5)


In [2]:
## Reshaping an array from (10,5) to (5,10)
## Using flatten arrays are maked into 1 dimentioned array. It does row wise flattening

b = arr.reshape(5,10)
print(b)
b.ndim
flatten = b.flatten()
print(flatten.ndim)
print(flatten)

## Column wise flattening using ravel
collumn_wise_flattening = np.ravel(b, order='F')  ## for row wise orderr, order='c'
print(collumn_wise_flattening)

[[11 81 60 54 18 68 76 62 63 14]
 [51 29 82 78 56 52 25 60 99 21]
 [56 77 69 72 66 90 55 95 26 19]
 [56 99  4 61 61 77 62 48  4 45]
 [61 23 12 67 37 23 33 41 92  6]]
1
[11 81 60 54 18 68 76 62 63 14 51 29 82 78 56 52 25 60 99 21 56 77 69 72
 66 90 55 95 26 19 56 99  4 61 61 77 62 48  4 45 61 23 12 67 37 23 33 41
 92  6]
[11 51 56 56 61 81 29 77 99 23 60 82 69  4 12 54 78 72 61 67 18 56 66 61
 37 68 52 90 77 23 76 25 55 62 33 62 60 95 48 41 63 99 26  4 92 14 21 19
 45  6]


### Concatanate

In [3]:
a = np.random.randint(1,10, size =(2,3))
b = np.random.randint(20,30, size =(2,3))
print(a)
print(b)

[[7 3 4]
 [5 2 3]]
[[25 28 27]
 [20 20 28]]


In [4]:
con_row = np.concatenate((a,b), axis=0) # row wise
print(con_row)
con_col = np.concatenate((a,b), axis=1) # column wise
print(con_col)

[[ 7  3  4]
 [ 5  2  3]
 [25 28 27]
 [20 20 28]]
[[ 7  3  4 25 28 27]
 [ 5  2  3 20 20 28]]


In [5]:
## Dimension needs to be matched for concatenation
x = np.random.randint(1,10, size =(2,3))
y = np.random.randint(20,30, size =(1,3))
print(x)
print(y)
con_row = np.concatenate((x,y), axis = 0) ## will work, because row dimentioned matched
con_col = np.concatenate((x,y), axis = 1) ## will not work because column dimension missmatched

[[6 6 1]
 [2 7 9]]
[[28 29 27]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 2 and the array at index 1 has size 1

### Transpose Matrix

In [ ]:
mat = np.array([[10,20,30],[40,50,60]])
transpose = mat.T
print(transpose)

### Array Split

In [ ]:
a = np.random.randint(1,10, size =(10,))

## not equal division
splitted_array = np.array_split(a,3)
print(splitted_array)

## equal division
splitted_array = np.split(a,3) ## will not work because array can not be devided equally

### Arithmatic Operator & Mathmatical Function

In [ ]:
## Faster for vectorization
x = np.array([10,20,30,40])
y = np.array([2,3,4,5])

add = x+y
print(add)

sub = x-y
print(sub)

multi = x*y
print(multi)

div = x/y
print(div)

reminder = x%y
print(reminder)

In [ ]:
## mathematical function

## trigonometry
## sin, cos, tan takes value in radian
sin_val = np.sin(x)
print(sin_val)

cos_val = np.cos(x)
print(cos_val)

deg_con = np.rad2deg(x)
print(deg_con)

In [ ]:
## Log
# 10 diye koybar vaag kora jay
base_10_log_val = np.log10(x)
print(base_10_log_val)

# 2 diye koybar vag kora jay
two_diye_vag = np.log2(x)
print(two_diye_vag)

# square root
sqrt = np.sqrt(x)
print(sqrt)

# sum
s = np.sum(x)
print(s)

# cumulative sum
cumulitive = np.cumulative_sum(x)
print(cumulitive)

### Broadcasting

In [ ]:
x = np.array([10,20,30,40])
result = x**2
print(result)

In [ ]:
mat = np.array([[10,20,30],
                [40,50,60]
               ])
#print(mat)
result = mat+2
#print(result)

vector = np.array([10,20,30])
sumation = mat+vector
print(sumation)

### Comparison - >, <, <=, >=, ==, !=

In [ ]:
x = np.array([10,20,30,40])
y = np.array([2,3,30,5])

greater_than = x>y
print(greater_than)

equal = x ==y
print(equal)

# all() -> shob true kina
# any() -> je kono ekta true kina
print(np.all(greater_than))
print(np.any(equal))

### Sorting

In [ ]:
## In place sorting does not copy the original one, instead change the original one
x = np.array([10,2,30,40])
z = x.copy()
print(z)
z.sort()
print(z)

## copy the original array. does not change original one
x = np.array([10,2,5,40])
sort_arr = np.sort(x)
print(sort_arr)
print(x)

In [ ]:
## 2d array sorting
mat = np.array([[10,3,5],[8,4,9]])

# horizontal sort. axis =1
hor_sort = np.sort(mat, axis=1)
print(hor_sort)

# vertical sort. axis =0
ver_sort = np.sort(mat, axis=0)
print(ver_sort)

### Searching

In [ ]:
print(x)

In [ ]:
# np.where(condition, x, y) if true x, otherwise replace with y
index = np.where(x==5)
print(index)

index = np.where(x>=5)
print(index)

index = np.where(x>5,x,0)  # returns array. ## np.where(condition, x, y) if true x, otherwise replace with y
print(index)

## Maximum index & Minimum index
print(x)
maximum_value_index = np.argmax(x)
minimum_value_index = np.argmin(x)

print(maximum_value_index)
print(minimum_value_index)

### Counting

In [ ]:
x = np.random.randint(1,100, size =(100,))
print(x)

## np.count_nonzero
value_greater_than_60 = np.count_nonzero(x>100)
print(value_greater_than_60)

## np.unique
unique_value, count = np.unique(x, return_counts=True)
print(unique_value)
print(count)

### Statistical Function

In [ ]:
# np.max()
# np.min()
# np.mean() -> average
# np.median()
# np.std() -> standard deviation
# np.corrcoef()

### Linear Algebra

In [ ]:
import numpy as np
A = np.array([
    [1,2],
    [3,4]
])
B = np.array([
    [5,6],
    [7,8]
])

# Matrix Multiplication
dot_product = np.dot(A,B) # Matrix Multiplication
print(dot_product)

# Trace ber kora
print(np.trace(B)) # diagonal borabor value gula sumation kore

# Determinent ber kora

sq_mat = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(sq_mat.shape)
det_of_sq = np.linalg.det(sq_mat)
print(det_of_sq)

# Rank ber kora
rank_of_sq = np.linalg.matrix_rank(sq_mat)
print(rank_of_sq)

In [ ]:
arr = np.array([1,2,3,4,5,6])
b = arr.reshape(2,3)
print(b.shape)
print(np.sin(np.pi/2))

In [ ]:
print("Hello World")