### Problem of traditional array operation - it takes to iterate the whole array using loop

In [1]:
arr = [1,2,3,4,5]
print(arr * 5)
arr = [x*5 for x in arr]
print(arr)

[1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5, 1, 2, 3, 4, 5]
[5, 10, 15, 20, 25]


### Using np.array() eliminate traditional for loop operation. Much faster than for loop

In [2]:
import numpy as np
arr1 = np.array([1,2,3,4,5])
arr1 = arr1*5
print(arr1)

[ 5 10 15 20 25]


### NdArray Creation

In [8]:
import numpy as np
# 1D Array
arr1 = np.array([1,2,3,4,5,6])
print(type(arr1))
print(arr1.ndim)
print(arr1.shape)

# 2d array
arr2 = np.array([[1,2,3],
                [4,5,6]])
print(type(arr2))
print(arr2.ndim)
print(arr2.shape)

# 3d array
arr3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(arr3.ndim)

<class 'numpy.ndarray'>
1
(6,)
<class 'numpy.ndarray'>
2
(2, 3)
3


## Array Attribute

In [11]:
# Dimension 
print(".........Dimention..........")
print(arr1.ndim)
print(arr2.ndim)
print(arr3.ndim)

# Shape
print(".........Shape..........")
print(arr1.shape)
print(arr2.shape)
print(arr3.shape)

# Data Type
print(".........Data Type(dtype)..........")
print(arr1.dtype)
print(arr2.dtype)
print(arr3.dtype)

# Size
print(".........Size..........")
print(arr1.size)
print(arr2.size)
print(arr3.size)

.........Dimention..........
1
2
3
.........Shape..........
(6,)
(2, 3)
(2, 2, 3)
.........Data Type(dtype)..........
int64
int64
int64
.........Size..........
6
6
12


### Upcasting data type

In [21]:
arr = np.array([1,2,3])
print(arr.dtype)  # by default dtype is int64

# Upcasted to float
arr = np.array([1,2,3.4,5])
print(arr.dtype)  # upcasted dtype to float64

# Upcasted to string
arr = np.array([1,2.5,3,'hello'])
print(arr.dtype)  # upcasted dtype to U32


int64
float64
<U32


### Selecting a data type by my own for an array

In [18]:
# Using dtype = np.int16 we can set the array dtype

arr = np.array([1,2,300], dtype = np.int16)
print(arr.dtype)

int16


In [16]:
## astype
arr = arr.astype(np.int64)
print(arr.dtype)
print(arr)

int64
[  1   2 300]


### Creating ndarray from exiting list

In [3]:
import numpy as np
# from list

lst = [1,2,3,4,5]
arr = np.array(lst, dtype = np.int16)
print(type(arr))
print(arr.dtype)
print(arr.ndim)
print(arr)

# from tuple
tpl = (10,20,30)
tpl = np.array(tpl)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr)

# from set
# set can not be converted to np.array. Instead its need to pass as a list
st = {1,2,3,4,5}
st = np.array(list(st))
print(type(st))
print(st.dtype)
print(st.shape)
print(st.ndim)
print(st)

# from dictionary
dc = {'a':10, 'b':20, 'c':30}
print(type(dc))
keys = dc.keys()
values = dc.values()
items = dc.items()
print(keys)
print(values)
print(items)

# keys to nd array
arr = np.array(list(keys))
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr)


# values to ndarray
arr = np.array(list(values))
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)
print(arr)

# items to ndarray
arr = np.array(list(items))
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.ndim)

<class 'numpy.ndarray'>
int16
1
[1 2 3 4 5]
<class 'numpy.ndarray'>
int16
(5,)
1
[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
(5,)
1
[1 2 3 4 5]
<class 'dict'>
dict_keys(['a', 'b', 'c'])
dict_values([10, 20, 30])
dict_items([('a', 10), ('b', 20), ('c', 30)])
<class 'numpy.ndarray'>
<U1
(3,)
1
['a' 'b' 'c']
<class 'numpy.ndarray'>
int64
(3,)
1
[10 20 30]
[['a' '10']
 ['b' '20']
 ['c' '30']]
<class 'numpy.ndarray'>
<U21
(3, 2)
2


## Creating nd array from scratch

In [22]:
# np.zeros(shape)
# creates array of all element as 0
arr = np.zeros((2,3), dtype = np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)

# np.zeros_like
# creates a 0 matrix but taking shape from an existing array
arr = np.zeros_like(arr3)
print(arr)
print(arr.shape)

# np.ones
# creates array of all element as 1
arr = np.ones((3, 4, 3), dtype = np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)

# np.ones_like
# creates a 1 matrix but taking shape from an existing array
arr = np.ones_like(arr3)
print(arr)

# np.empty
# creates array of all element as random junc value
arr = np.empty((4,3), dtype=np.int8)
print(arr)
print(type(arr))
print(arr.dtype)
print(arr.shape)
print(arr.size)

# np.empty_like
# creates a junc value matrix but taking shape from an existing arrajunc value
arr = np.empty_like(arr3)
print(arr)
print(arr.shape)

# np.full(shape, fill_value)
# creates array of all element as 10
arr = np.full((4,3),10)
print(arr)

# np.full_like
arr = np.full_like(arr3,10)
print(arr)

[[0 0 0]
 [0 0 0]]
<class 'numpy.ndarray'>
int8
(2, 3)
6
[[[0 0 0]
  [0 0 0]]

 [[0 0 0]
  [0 0 0]]]
(2, 2, 3)
[[[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]
  [1 1 1]
  [1 1 1]]]
<class 'numpy.ndarray'>
int8
(3, 4, 3)
36
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
[[97  0  0]
 [ 0 98  0]
 [ 0  0 99]
 [ 0  0  0]]
<class 'numpy.ndarray'>
int8
(4, 3)
12
[[[1 1 1]
  [1 1 1]]

 [[1 1 1]
  [1 1 1]]]
(2, 2, 3)
[[10 10 10]
 [10 10 10]
 [10 10 10]
 [10 10 10]]
[[[10 10 10]
  [10 10 10]]

 [[10 10 10]
  [10 10 10]]]


### Array creation with random value

In [26]:
# np.random.rand(shape)
import numpy as np
arr = np.random.rand(2,3)
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(type(arr))

[[0.20364102 0.74151122 0.27233105]
 [0.51313597 0.14045174 0.64658494]]
(2, 3)
float64
2
6
<class 'numpy.ndarray'>


In [28]:
# np.random.randint(desired value range, shape)
# creates a np array of (2,3) and all the values between 1-5
arr = np.random.randint(1,5,(2,3))
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(type(arr))

# creating 1D array using randint
arr = np.random.randint(1,5,(5,))
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(type(arr))

[[2 1 4]
 [3 1 3]]
(2, 3)
int32
2
6
<class 'numpy.ndarray'>
[4 4 1 1 4]
(5,)
int32
1
5
<class 'numpy.ndarray'>


In [29]:
# np.random.uniform(desired value range, shape)
# this method generates using floating value
arr = np.random.uniform(50,100,(2,3))
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(type(arr))

[[63.03592482 90.91529015 97.43694837]
 [74.89891239 80.53614981 75.46171883]]
(2, 3)
float64
2
6
<class 'numpy.ndarray'>


### Array creation with np.arange function

In [35]:
## np.arange(start, end, steps) & np.reshape()

arr = np.arange(1,10,1)  # creates 1d array
print(arr)
arr = np.arange(1,10,1).reshape(3,3)  # using reshape we changed the array to 3d array
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(type(arr))
print("........................")

# np.linspace(start, end, koyta). Evenly distribute kore
# 1 theke 10 er moddhe 5 ta evenly point pick kore matrix create korbe
arr = np.linspace(1, 10, 5)
print(arr)
print(arr.shape)
print(arr.dtype)
print(arr.ndim)
print(arr.size)
print(type(arr))

## np.logspace(start, end, koyta)
arr = np.logspace(0,4,5, base=2)
print(arr)

[1 2 3 4 5 6 7 8 9]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)
int64
2
9
<class 'numpy.ndarray'>
........................
[ 1.    3.25  5.5   7.75 10.  ]
(5,)
float64
1
5
<class 'numpy.ndarray'>
[ 1.  2.  4.  8. 16.]


### Creating Matrix for linear algebra.

In [36]:
# Diagonal Matrix
# diagonal borabor value thakbe. baki shob value hbe 0
diagonal_matrix = np.diag([1,2,3,4])
print(diagonal_matrix)
print(diagonal_matrix.shape)

# identity matrix. np.eye(row, coll, k)
# diagonal borabor value thakbe 1. baki shob value hbe 0
iden = np.eye(4)
print(iden)
print(iden.shape)

# changing diagonal using k value of eye()
iden = np.eye(3,4,-1)
print(iden)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]
(4, 4)
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
(4, 4)
[[0. 0. 0. 0.]
 [1. 0. 0. 0.]
 [0. 1. 0. 0.]]


### Indexing

In [ ]:
arr1 = [1,2,3,4,5]
arr2 = [[1, 2, 3], [4, 5, 6]]

arr1 = np.array(arr1)
arr2 = np.array(arr2)
print(arr1[2])
arr1[2] = 100
print(arr1)

print(arr2[0][1])
arr2[0][1] = 100
print(arr2)

### Slicing

In [38]:
# 1d array slicing
# arr[start:end: step]
arr1_modified = arr1[1:4]
#print(arr1_modified)

# 2d array slicing
#arr[rowstart:rowend:rowstep,colstart:colend:colstep]
print(arr2)

print("...............")
# getting row 0
row0 = arr2[0:1,]

# getting row 1
row1 = arr2[1:,]

print(row0)
print(row1)
print("...............")

# getting a colum
colum0 = arr2[::, 0:1]
print(colum0)

[[  1 100   3]
 [  4   5   6]]
...............
[[  1 100   3]]
[[4 5 6]]
...............
[[1]
 [4]]


### Advanced indexing and iteration

In [40]:
## copy in array
print(arr1)
arr_modified = arr1[1:3].copy()
arr_modified[1] = 600
print(arr_modified)
print(arr1)

print(".....................")

## Advanced Slicing
ls = np.array([10,20,30,40,50,60])
print(ls)
values = ls[[1,3]]
print(values)

## advanced slicing for 2d array
print(".....................")
print(arr2)
print(arr2[[0,1],[1,2]])

# boolean operation
print(arr2[arr2>2])
arr2[arr2>2] = 0
print(arr2)

[  1   2 100   4   5]
[  2 600]
[  1   2 100   4   5]
.....................
[10 20 30 40 50 60]
[20 40]
.....................
[[  1 100   3]
 [  4   5   6]]
[100   6]
[100   3   4   5   6]
[[1 0 0]
 [0 0 0]]


In [41]:
## Iteration
arr = np.array([[10,20,30,40],[100,200,300,400]])
print(arr)
for i in np.nditer(arr):
    print(i)

[[ 10  20  30  40]
 [100 200 300 400]]
10
20
30
40
100
200
300
400


In [42]:
arr = np.array([[10,20,30],[40,50,60]])
print(arr[:,1])

[20 50]
